// Mocks generated by Mockito 5.4.6 from annotations
// in coffe_shop/test/core/controller/user_cubit/user_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coffe_shop/core/helpers/failure.dart' as _i5;
import 'package:coffe_shop/core/repo/user_repo.dart' as _i3;
import 'package:coffe_shop/features/auth/data/models/user_model.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepo extends _i1.Mock implements _i3.UserRepo {
  MockUserRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getUserAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getUserAddress, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getUserAddress, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Position>> getUserCoardinates() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCoardinates, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Position>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Position>(
                    this,
                    Invocation.method(#getUserCoardinates, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Position>>);

  @override
  String getuserId() =>
      (super.noSuchMethod(
            Invocation.method(#getuserId, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getuserId, []),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>> getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#getUser, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>>);

  @override
  (String, String) getuserNameAndPhone() =>
      (super.noSuchMethod(
            Invocation.method(#getuserNameAndPhone, []),
            returnValue: (
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getuserNameAndPhone, []),
              ),
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getuserNameAndPhone, []),
              ),
            ),
          )
          as (String, String));
}
