// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybVbIpgBzfDTISULqujyIQ1zti9-8Hs0',
    appId: '1:613637613101:web:f1976aa2e74e0bf010faa4',
    messagingSenderId: '613637613101',
    projectId: 'order-tracker-76c47',
    authDomain: 'order-tracker-76c47.firebaseapp.com',
    storageBucket: 'order-tracker-76c47.firebasestorage.app',
    measurementId: 'G-BJ5E4Z2MV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYQ5EdZSQ8WhbPCcbky8E78X6TWRtb1Y',
    appId: '1:613637613101:android:7748924cd78fa91b10faa4',
    messagingSenderId: '613637613101',
    projectId: 'order-tracker-76c47',
    storageBucket: 'order-tracker-76c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepjN32iyCxAe9ej-S39EueadXSlskEdk',
    appId: '1:613637613101:ios:3949cafa1a3dafff10faa4',
    messagingSenderId: '613637613101',
    projectId: 'order-tracker-76c47',
    storageBucket: 'order-tracker-76c47.firebasestorage.app',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCepjN32iyCxAe9ej-S39EueadXSlskEdk',
    appId: '1:613637613101:ios:3949cafa1a3dafff10faa4',
    messagingSenderId: '613637613101',
    projectId: 'order-tracker-76c47',
    storageBucket: 'order-tracker-76c47.firebasestorage.app',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCybVbIpgBzfDTISULqujyIQ1zti9-8Hs0',
    appId: '1:613637613101:web:7a61704cc36dd7f610faa4',
    messagingSenderId: '613637613101',
    projectId: 'order-tracker-76c47',
    authDomain: 'order-tracker-76c47.firebaseapp.com',
    storageBucket: 'order-tracker-76c47.firebasestorage.app',
    measurementId: 'G-MRJVDXP02X',
  );
}
