// Mocks generated by Mockito 5.4.6 from annotations
// in coffe_shop/test/features/delevery/presentation/controller/cubit/delivery_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coffe_shop/core/helpers/failure.dart' as _i5;
import 'package:coffe_shop/features/delevery/data/model/deleivery_model.dart'
    as _i9;
import 'package:coffe_shop/features/delevery/data/repo/delievery_repo.dart'
    as _i3;
import 'package:coffe_shop/features/order/data/models/order_model.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i7;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DelieveryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDelieveryRepo extends _i1.Mock implements _i3.DelieveryRepo {
  MockDelieveryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.OrderModel>>>
  getDeliveryOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getDeliveryOrders, []),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.OrderModel>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.OrderModel>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i7.Position>> getDeliveryPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getDeliveryPosition, []),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, _i7.Position>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, _i7.Position>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Set<_i8.Polyline>>>
  drawPolylineCoordinates({
    required _i8.LatLng? start,
    required _i8.LatLng? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#drawPolylineCoordinates, [], {
              #start: start,
              #end: end,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Set<_i8.Polyline>>>.value(
                  _FakeEither_0<_i5.Failure, Set<_i8.Polyline>>(
                    this,
                    Invocation.method(#drawPolylineCoordinates, [], {
                      #start: start,
                      #end: end,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Set<_i8.Polyline>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changeOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeOrderStatus, [orderId, status]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changeOrderStatus, [orderId, status]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateDeliveryLatLong({
    required double? lat,
    required double? long,
    required String? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeliveryLatLong, [], {
              #lat: lat,
              #long: long,
              #orderId: orderId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateDeliveryLatLong, [], {
                  #lat: lat,
                  #long: long,
                  #orderId: orderId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> actionOnOrder({
    required _i9.DeleiveryModel? deleiveryModel,
    required String? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actionOnOrder, [], {
              #deleiveryModel: deleiveryModel,
              #orderId: orderId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#actionOnOrder, [], {
                  #deleiveryModel: deleiveryModel,
                  #orderId: orderId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  double getDiffDistance({
    required double? lat1,
    required double? long1,
    required double? lat2,
    required double? long2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiffDistance, [], {
              #lat1: lat1,
              #long1: long1,
              #lat2: lat2,
              #long2: long2,
            }),
            returnValue: 0.0,
          )
          as double);
}
